# TOBY = Character.find_by_name("TOBY")
# SAM = Character.find_by_name("SAM")
# JOSH = Character.find_by_name("JOSH")
# LEO = Character.find_by_name("LEO")
# DONNA = Character.find_by_name("DONNA")
# BARTLET = Character.find_by_name("BARTLET")
# CHARLIE = Character.find_by_name("CHARLIE")
# CJ = Character.find_by_name("C.J.")